### ISSUE TITLE
scipy installed but not available from QGIS

### ISSUE THREAD

**Issue by aloboa** [flathub/org.qgis.qgis#370]
I installed QGIS 3.32 from flatpak and then
`flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user`

but

```
$ flatpak run org.qgis.qgis

(process:2): Gtk-WARNING **: 17:43:54.672: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 17:43:54.743: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:43:54.744: Failed to load module "canberra-gtk-module"
Warning: Could not find color scheme  ""
Warning: Qt: Session management error: Could not open network socket
Unable to import scipy:
 No module named 'scipy'
Unable to import matplotlib:
 No module named 'matplotlib'
Unable to import pip:
 No module named 'pip'
Unable to import typeguard:
 No module named 'typeguard'
Unable to import sklearn:
 No module named 'sklearn'
Unable to import astropy:
 No module named 'astropy'
Unable to import OpenGL:
 No module named 'OpenGL'
Unable to import xgboost:
 No module named 'xgboost'
Unable to import lightgbm:
 No module named 'lightgbm'
Unable to import catboost:
 No module named 'catboost'
Unable to import sympy:
 No module named 'sympy'
Unable to import numba:
 No module named 'numba'
Unable to import netCDF4:
 No module named 'netCDF4'
Unable to import enpt_enmapboxapp:
 No module named 'enpt_enmapboxapp'
Unable to import sklearn:
 No module named 'sklearn'
load /home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxresources_rc.py
load /home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/enmapboxapplications/ressources_rc.py
load /home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/qpsresources_rc.py
Traceback (most recent call last):
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 233, in collectEnMAPBoxAlgorithms
    from enmapboxprocessing.algorithm.algorithms import algorithms
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/algorithms.py", line 25, in <module>
    from enmapboxprocessing.algorithm.featureclusteringhierarchicalalgorithm import FeatureClusteringHierarchicalAlgorithm
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/featureclusteringhierarchicalalgorithm.py", line 7, in <module>
    from scipy.cluster import hierarchy
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'
```

**Comment by aleixpol** [comment]
What's the output of  `flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user`?

**Comment by aloboa** [comment]
```
$ flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user
Collecting scipy
  Using cached scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /app/lib/python3.10/site-packages (from scipy) (1.25.2)
Installing collected packages: scipy
Successfully installed scipy-1.11.3
```
Then, after installing enmapbox plugin, I get:
2023-10-28T19:04:33     CRITICAL    Unable to load enmapboxprocessing.algorithm.algorithms : Unable to load enmapboxprocessing.algorithm.algorithms
             No module named 'scipy'
2023-10-28T19:04:33     INFO    Plugin installed successfully

**Comment by jakimowb** [comment]
@aloboa can you import scipy from the QGIS python console (CTRL+ALT+P)?

**Comment by aloboa** [comment]
3.32 (through flatpak)

```
# Python Console
# Use iface to access QGIS API interface or type '?' for more info
# Security warning: typing commands from an untrusted source can harm your computer
import scipy
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/alobo/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'
```


3.28.12 LTR
No problem with import python from the QGIS console.
All requirements satisfied according to:
`sudo python3 -m pip install -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt
`
QGIS crashes after installation of enmapbox 3.12.1
After QGIS restart, enmapbox is available to be selected, but
qgis crashes as soon as the plugin is selected:
```
$ qgis
QGIS died on signal 11Aborted (core dumped)
```

**Comment by jakimowb** [comment]
I wonder why `ee_plugin` appears in the stack trace?

**Comment by aloboa** [comment]
After deactivating the GE plugin:
```
# Python Console
# Use iface to access QGIS API interface or type '?' for more info
# Security warning: typing commands from an untrusted source can harm your computer
import scipy
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'
```

**Comment by jakimowb** [comment]
I can reproduce the described behavior on Linux Mint 21.2
I installed scipy with: `flatpak run --devel --command=python org.qgis.qgis -m pip install scipy --user`

Without `--user` I get the following message:
```
flatpak run --devel --command=python org.qgis.qgis -m pip install scipy
Defaulting to user installation because normal site-packages is not writeable
```
Even after successful installation, scipy is not found by pip:

```
$ flatpak run --devel --command=python org.qgis.qgis -m pip install scipy
Defaulting to user installation because normal site-packages is not writeable
Collecting scipy
  Using cached scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /app/lib/python3.10/site-packages (from scipy) (1.25.2)
Installing collected packages: scipy
Successfully installed scipy-1.11.3
$ flatpak run --devel --command=python org.qgis.qgis -m pip show scipy
WARNING: Package(s) not found: scipy

```

**Comment by gbaia** [comment]
I think it's a more general issue.
I have installed QGIS 3.32.3 from flatpak on Fedora 39 and then run:
`flatpak run --devel --command=pip3 org.qgis.qgis install plotly --user`
However, plotly is not actually installed. 
In fact, import plotly from the QGIS python console or starting the Data Plotly plugin returns:
ModuleNotFoundError: No module named 'plotly'

**Comment by jakimowb** [comment]
I think this problem relates to  #333

**Comment by aleixpol** [comment]
Would somebody be able to test it with 3.34.0? I think it should be fixed, at least it works for me.

**Comment by aloboa** [comment]
> Would somebody be able to test it with 3.34.0? I think it should be fixed, at least it works for me.

Not sure how to proceed. After upgrading to QGIS 3.34 through Flatpak, I run:
```
$  flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user
error: runtime/org.kde.Sdk/x86_64/5.15-23.08 not installed

``` 

Within QGIS python console:
```
import scipy
Traceback (most recent call last):
  File "/usr/lib/python3.11/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'scipy'
```

**Comment by jakimowb** [comment]
@aloboa you need to install the kde Sdk 
1. run `flatpak install org.kde.Sdk`
2. selecting the 5.15-23.08 version

@aleixpol thank's. It now works on linux mint 21.2

**Comment by aloboa** [comment]
@jakimowb Thanks, `import scipy` works now from within QGIS after `flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user`
Where is it stated that orgkede.Sdk is a requirement? Not mentioned in https://qgis.org/es/site/forusers/alldownloads.html#flatpak
Can I go on and install enmapbox? No trouble with netCDF4?
@aleixpol Thanks

**Comment by jakimowb** [comment]
@aloboa the EnMAP-Box still fails to run due to a missing `PyQt5.pyrcc_main` module. I try to find out how this can be installed to flatpak

**Comment by aleixpol** [comment]
> Where is it stated that org.kde.Sdk is a requirement? 

It's needed for the `--devel` argument. Feel free to suggest a change to the documentation although I think it might just make it a bit more complex?

I'll close the ticket for now.
